apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sbchoi
resources:
  - guestbook-ui-deployment.yaml
  - guestbook-ui-svc.yaml
  - redis-leader-deployment.yaml
  - redis-leader-service.yaml
  - redis-follower-deployment.yaml
  - redis-follower-service.yaml
  - redis-commander-deployment.yaml
  - redis-commander-service.yaml
